### ISSUE TITLE
tests directory exported as top level package for elasticmock

### ISSUE THREAD

**Issue by jmlw** [vrcmarcos/elasticmock#12]
Tests is deployed and included in site-packages as a top level library as shown in the image below. This can cause errors when using frameworks like Serverless Framework where it attempts to symlink all top level site-packages  into the root of your project directory if using the same folder structure. It seems it would be best practice to nest tests directory within the deployed package, or to exclude it from deployment.

Site packages in virtual environment:
![image](https://user-images.githubusercontent.com/2490661/41619384-a65f9766-73cb-11e8-8bc4-b08724835f72.png)

**Comment by vrcmarcos** [comment]
I approved your PR (https://github.com/vrcmarcos/elasticmock/pull/13) and release v1.3.3.

Thanks for your contribution!
