### ISSUE TITLE
Release 1.3.4 is broken due to missing readme

### ISSUE THREAD

**Issue by lynncyrin** [vrcmarcos/elasticmock#18]
The `README.md` isn't included in the python package, so this change https://github.com/vrcmarcos/elasticmock/commit/e674b744df936b5b7b0f22f2f600bc7cfc7ba3db#diff-2eeaed663bd0d25b7e608891384b7298 breaks installs of version 1.3.4

**Comment by vrcmarcos** [comment]
Fixed with PR https://github.com/vrcmarcos/elasticmock/pull/19

**Comment by vrcmarcos** [comment]
Thanks for point it!

Could you check if PR #19 fixed it, please?

**Comment by infinite-Joy9l** [comment]
I am still getting the issue. :(

**Comment by tdhopper** [comment]
``` !  /t/k/ElasticMock-1.3.5  exa -T                                                                                                    Mon Mar 11 09:22:13 2019
.
├── elasticmock
│  ├── __init__.py
│  ├── fake_elasticsearch.py
│  └── utilities
│     └── __init__.py
├── ElasticMock.egg-info
│  ├── dependency_links.txt
│  ├── PKG-INFO
│  ├── requires.txt
│  ├── SOURCES.txt
│  └── top_level.txt
├── PKG-INFO
├── setup.cfg
├── setup.py
└── tests
   ├── __init__.py
   └── test_elasticmock.py```

```
Looking in indexes: https://pypi.org/simple, https://artifacts.d.cylance.com/api/pypi/datsci-pypi/simple
Collecting elasticmock
  Downloading https://files.pythonhosted.org/packages/ee/27/d70e1ca53b8080138f613e4d600831397acd6bf7fdc466bea32692fc9bf5/ElasticMock-1.3.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mg/9dh5w1r93w3630s4p0y33_c40000gn/T/pip-install-8jE_6k/elasticmock/setup.py", line 10, in <module>
        with open(path.join(this_directory, 'README.md'), 'r') as f:
    IOError: [Errno 2] No such file or directory: '/private/var/folders/mg/9dh5w1r93w3630s4p0y33_c40000gn/T/pip-install-8jE_6k/elasticmock/README.md'
```

**Comment by tdhopper** [comment]
Opened #20 to fix.

**Comment by vrcmarcos** [comment]
Just merged @tdhopper PR. Could you check if now it's fixed, please?

**Comment by tdhopper** [comment]
Seems okay to me
