### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by vrcmarcos** [vrcmarcos/elasticmock#33]
Hi all,

I'm looking for active maintainers for this library. I think that we can add 2 or 3 more people to active develop this library, or at least guide the contributors.

If you are interested, please comment in this issue.

(Mentioning all contributors to see if they had interest in it):

@xrmx @snakeye @frivoire @asherf @mohantyashish109 @mattt-b @jmlw @infinite-Joy @garncarz @barseghyanartur @tcatrain @charl-van-niekerk @bowlofstew @askoretskiy 

Ty!

**Comment by tcatrain** [comment]
Hi !

Definitely would like to help maintaining elastimock ! I'm in !

**Comment by snakeye** [comment]
We are using this package a lot. I will be happy to join the project!

**Comment by charl-van-niekerk** [comment]
We are actively using this package and would be happy to help out.

**Comment by vrcmarcos** [comment]
Ok! Added you three as colaborators! Ty!
