### ISSUE TITLE
aioelasticsearch client support

### ISSUE THREAD

**Issue by chesstrian** [vrcmarcos/elasticmock#37]
Hi @vrcmarcos, can you please guide me to implement support for async client?.

**Comment by vrcmarcos** [comment]
Sure! I was recruiting people to help me mantaining this library, and it would be a pleasure to add you as a collaborator. Wdyt?

**Comment by chesstrian** [comment]
Sure, I'm glad to help 😃

**Comment by vrcmarcos** [comment]
Just sent you an invite to be a colaborator :)

How can I help you with it?

**Comment by chesstrian** [comment]
@vrcmarcos I have checked the code, supporting the async library is possible but leaving for now. Closing this.
