### ISSUE TITLE
Elasticsearch expects 'skipped' key in shards

### ISSUE THREAD

**Issue by philtweir** [vrcmarcos/elasticmock#50]
### What happened

When using with elasticsearch_dsl (7.1.0) and elasticsearch (7.5.1), calling scan() ends up with a KeyError.

```
    for ent in search.scan():
  File ".../elasticsearch_dsl/search.py", line 715, in scan
    for hit in scan(
  File ".../elasticsearch/helpers/actions.py", line 449, in scan
    if (resp["_shards"]["successful"] + resp["_shards"]["skipped"]) < resp[
KeyError: 'skipped'
```

### What did you expect to happen

Iterable of entities to be returned.

---

It looks to be a result of [this change](https://github.com/elastic/elasticsearch-py/commit/fc78c992ef6ceca157f369186760c8c550fb3bc4) in elasticsearch-py. This leads to a missing key in ElasticMock's result's `_shards` statuses and may be fixable by adding `"skipped": 0` [here](https://github.com/vrcmarcos/elasticmock/blob/cecd02a35b6f645f507af3e9737e08484a8feb5d/elasticmock/fake_elasticsearch.py#L389) in _fake_elasticsearch.py_ .

Happy to do a PR for the two _shards dicts, if that is the right approach

**Comment by vrcmarcos** [comment]
Yeah, a PR would be awesome! It seems a good approach

**Comment by philtweir** [comment]
Not the most exciting PR, but it's a start :D

**Comment by vrcmarcos** [comment]
Lol looks awesome! :D will merge it

**Comment by philtweir** [comment]
Great thanks!
