### ISSUE TITLE
Deprecated use of _type in bulk API

### ISSUE THREAD

**Issue by fenimore** [vrcmarcos/elasticmock#65]
The elastic mock requires the `elasticsearch.ElasticSearch.bulk` method includes a `_type` field in the "actions" of the `body` parameter. (the body is newline separated action-document combinations)

https://github.com/vrcmarcos/elasticmock/blob/master/elasticmock/fake_elasticsearch.py#L331

When running this however with a Dockerized ES server I get (version `7.10.2`)

```
elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: [types removal] Specifying types in bulk requests is deprecated.
```

Here is the explanation for why: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/removal-of-types.html

**Comment by vrcmarcos** [comment]
Hi!

Awesome note :) Ty for that!

Do you mind to send a PR fixing that? I'm not actively mainting this library, just merging the PRs
